apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx:latest
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: app1-volume
          mountPath: /usr/share/nginx/html
          # subPath: index.html
      volumes:
      - name: app1-volume
        configMap:
          name: app1-html
          items:
          - key: app1.html
            path: index.html

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nginx:latest
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: app2-volume
          mountPath: /usr/share/nginx/html
          # subPath: index.html
      volumes:
      - name: app2-volume
        configMap:
          name: app2-html
          items:
          - key: app2.html
            path: index.html

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: nginx:latest
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: app3-volume
          mountPath: /usr/share/nginx/html
          # subPath: index.html
      volumes:
      - name: app3-volume
        configMap:
          name: app3-html
          items:
          - key: app3.html
            path: index.html

--- 

  apiVersion: v1
  kind: Service
  metadata:
    name: app1-service
  spec:
    selector:
      app: app1
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

  apiVersion: v1
  kind: Service
  metadata:
    name: app2-service
  spec:
    selector:
      app: app2
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

  apiVersion: v1
  kind: Service
  metadata:
    name: app3-service
  spec:
    selector:
      app: app3
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress
  spec:
    rules:
    - host: app1.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: app1-service
              port:
                number: 80
    - host: app2.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: app2-service
              port:
                number: 80
    - host: app3.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: app3-service
              port:
                number: 80
