apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pt3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jbettini/IOTP3-Jbettini
    targetRevision: HEAD
    path: argoManifest
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true